-- Insert County

INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Bedfordshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Bedfordshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Berkshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Bristol ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Buckinghamshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Cambridgeshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Cheshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Cornwall');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Durham');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Cumbria ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Derbyshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Devon');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Dorset');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'East Riding of Yorkshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'East Sussex ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Essex');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Gloucestershire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Greater London');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Greater Manchester');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Hampshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Herefordshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Hertfordshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Isle of Wight');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Kent');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Lancashire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Leicestershire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Lincolnshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Merseyside');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Norfolk ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'North Yorkshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Northamptonshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Northumberland');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Nottinghamshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Oxfordshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Rutland ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Shropshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Somerset');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'South Yorkshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Staffordshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Suffolk ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Surrey');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Tyne and Wear');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Warwickshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'West Midlands');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'West Sussex ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'West Yorkshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Wiltshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Worcestershire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Antrim');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Armagh');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Down ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Fermanagh');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Londonderry');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'County Tyrone');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Aberdeenshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Angus');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Clackmannanshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Dumfries and Galloway');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Dundee');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'East Lothian');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Edinburgh?');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Falkirk ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Fife');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Highlands');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Lothian ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Moray');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Perth and Kinross');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Scottish Borders');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Stirlingshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Strathclyde ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'West Lothian');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Western Isles');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Anglesey');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Carmarthenshire ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Ceredigion');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Conwy');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Denbighshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Flintshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Gwent');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Gwynedd ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Mid Glamorgan');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Monmouthshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Pembrokeshire');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Powys');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'South Glamorgan ');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'West Glamorgan');
INSERT INTO [County] (Id, Name) VALUES (NEWID(), 'Wrexham ');

--//@UNDO

DELETE FROM [County];
