-- Alter Spot

ALTER TABLE [Spot] DROP COLUMN [AddedOn] 
ALTER TABLE [Spot] ADD [AddedOn] DATETIME NOT NULL

--//@UNDO

ALTER TABLE [Spot] DROP COLUMN [AddedOn] 
ALTER TABLE [Spot] ADD [AddedOn] UNIQUEIDENTIFIER NOT NULL
