-- Insert County

INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Bedfordshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Bedfordshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Berkshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Bristol ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Buckinghamshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Cambridgeshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Cheshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Cornwall');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Durham');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Cumbria ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Derbyshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Devon');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Dorset');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'East Riding of Yorkshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'East Sussex ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Essex');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Gloucestershire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Greater London');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Greater Manchester');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Hampshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Herefordshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Hertfordshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Isle of Wight');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Kent');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Lancashire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Leicestershire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Lincolnshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Merseyside');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Norfolk ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'North Yorkshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Northamptonshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Northumberland');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Nottinghamshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Oxfordshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Rutland ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Shropshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Somerset');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'South Yorkshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Staffordshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Suffolk ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Surrey');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Tyne and Wear');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Warwickshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'West Midlands');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'West Sussex ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'West Yorkshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Wiltshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Worcestershire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Antrim');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Armagh');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Down ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Fermanagh');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Londonderry');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'County Tyrone');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Aberdeenshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Angus');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Clackmannanshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Dumfries and Galloway');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Dundee');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'East Lothian');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Edinburgh?');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Falkirk ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Fife');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Highlands');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Lothian ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Moray');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Perth and Kinross');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Scottish Borders');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Stirlingshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Strathclyde ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'West Lothian');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Western Isles');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Anglesey');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Carmarthenshire ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Ceredigion');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Conwy');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Denbighshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Flintshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Gwent');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Gwynedd ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Mid Glamorgan');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Monmouthshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Pembrokeshire');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Powys');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'South Glamorgan ');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'West Glamorgan');
INSERT INTO `County` (Id, Name) VALUES (UUID(), 'Wrexham ');

--//@UNDO

DELETE FROM `County`;
