-- Alter Message

START TRANSACTION;
ALTER TABLE `Message` CHANGE `UserId` `SenderId` CHAR(36) NOT NULL;
ALTER TABLE `Message` CHANGE `AddedOn` `SentOn` DATETIME NOT NULL;
ALTER TABLE `Message` ADD COLUMN `RecipientId` CHAR(36) NULL;
ALTER TABLE `Message` MODIFY COLUMN `Body` VARCHAR(1000) NULL;
ALTER TABLE `Message` ADD COLUMN `Title` CHAR(25) NOT NULL;
ALTER TABLE `Message` ADD COLUMN `Read` BIT NOT NULL DEFAULT 0;
COMMIT;

--//@UNDO

START TRANSACTION;
ALTER TABLE `Message` DROP COLUMN `Read`;
ALTER TABLE `Message` DROP COLUMN `Title`;
ALTER TABLE `Message` MODIFY COLUMN `Body` VARCHAR(255) NOT NULL;
ALTER TABLE `Message` DROP COLUMN `RecipientId`;
ALTER TABLE `Message` CHANGE `SentOn` `AddedOn` DATETIME NOT NULL;
ALTER TABLE `Message` CHANGE `SenderId` `UserId` CHAR(36) NOT NULL;
COMMIT;
